# Prospect Enhancement System v3 - Batch Configuration

# Batch Processing Settings
batch_processing:
  default_batch_size: 10
  max_batch_size: 15
  min_batch_size: 5
  parallel_workers: 3
  timeout_per_prospect_minutes: 30
  checkpoint_interval_minutes: 30

# Session Management  
session:
  max_duration_hours: 3
  break_between_batches_minutes: 15
  auto_save_enabled: true
  auto_save_interval_minutes: 10
  
# Quality Gates
quality_gates:
  min_quality_score: 9.5
  max_template_count: 0
  min_data_points_per_file:
    organization_foundation: 150
    strategic_context: 150
    technical_infrastructure: 175
    security_intelligence: 200
    vendor_ecosystem: 150
    business_initiatives: 175
    engagement_strategy: 200

# Resource Limits
resources:
  max_memory_gb: 8
  max_cpu_percent: 80
  max_disk_io_mbps: 100
  max_network_requests_per_minute: 60

# Priority Settings
priorities:
  priority_1:
    name: "Critical Gaps"
    batch_size: 10
    timeout_minutes: 45
    quality_target: 10.0
    
  priority_2:
    name: "Quick Wins"
    batch_size: 10
    timeout_minutes: 30
    quality_target: 9.5
    
  priority_3:
    name: "Template Replacement"
    batch_size: 15
    timeout_minutes: 20
    quality_target: 9.5

# Error Handling
error_handling:
  max_retries: 3
  retry_delay_seconds: 300
  save_on_error: true
  continue_batch_on_error: true
  error_notification_enabled: true

# Progress Tracking
progress_tracking:
  update_interval_minutes: 5
  tracker_file: "ENHANCEMENT_TRACKER_2025_LIVE.md"
  backup_enabled: true
  backup_interval_hours: 1
  metrics_collection_enabled: true

# MCP Server Requirements
mcp_servers:
  required:
    - tavily
    - context7
    - supermemory
    - pinecone
    - neo4j
    - jina-ai
  optional:
    - sequential-thinking
    - knowledge-graph-memory
  timeout_seconds: 30
  retry_on_failure: true

# File Management
file_management:
  prospect_base_path: "/root/Desktop/project_nightingale_workspace/project_nightingale/prospects"
  backup_path: "/root/Desktop/project_nightingale_workspace/project_nightingale/backups"
  log_path: "/root/Desktop/project_nightingale_workspace/project_nightingale/1_Capabilities/prospect_enhancement_v3/logs"
  template_path: "/root/Desktop/project_nightingale_workspace/project_nightingale/1_Capabilities/prospect_enhancement_v3/templates"

# Validation Rules
validation:
  template_patterns:
    - "\\[.*\\]"
    - "Company Name"
    - "\\bvarious\\b"
    - "\\bmultiple\\b"
    - "\\bnumerous\\b"
    - "TBD"
    - "To be determined"
  
  required_sections:
    organization_foundation:
      - "Executive Summary"
      - "Corporate Structure"
      - "Leadership Profiles"
      - "Financial Performance"
    strategic_context:
      - "Market Environment"
      - "Recent Developments"
      - "Business Challenges"
      - "Strategic Initiatives"
    technical_infrastructure:
      - "Technology Landscape"
      - "Digital Transformation"
      - "Technology Stack"
      - "Technical Challenges"
    security_intelligence:
      - "Security Posture"
      - "Incident History"
      - "Threat Landscape"
      - "Compliance Requirements"
    vendor_ecosystem:
      - "Current Technology Vendors"
      - "Cybersecurity Stack"
      - "Vendor Relationships"
      - "Procurement Process"
    business_initiatives:
      - "Strategic Initiatives"
      - "Active Projects"
      - "Investment Priorities"
      - "Planning Cycles"
    engagement_strategy:
      - "Executive Engagement"
      - "Value Propositions"
      - "Sales Strategy"
      - "Success Plan"

# Optimization Settings
optimization:
  cache_research_data: true
  cache_expiry_hours: 24
  reuse_common_data: true
  batch_similar_companies: true
  prefetch_next_batch: true

# Notification Settings
notifications:
  batch_complete: true
  quality_threshold_breach: true
  error_occurred: true
  daily_summary: true
  weekly_report: true
  
# Performance Benchmarks
benchmarks:
  target_per_prospect_minutes: 20
  target_daily_prospects: 40
  target_weekly_prospects: 200
  target_quality_score: 9.7
  target_first_pass_success: 90